### ISSUE TITLE
Fix annoying messages in the console when starting the development server

### ISSUE THREAD

**Issue by vandrongelen** [ipfs-search/dweb-search-frontend#107]
When using the development server I got these messages in the console:

<img width="640" alt="Screenshot 2021-11-25 at 11 24 04" src="https://user-images.githubusercontent.com/81126/143424135-db20148f-4a54-4c3c-af5a-db2477a2c6fe.png">

**Comment by dokterbob** [comment]
This should be automatically resolved when upgrading to Vue/Vuetify 3. #125

**Comment by femans** [comment]
closed with #214
