### ISSUE TITLE
Allow opening detail links in a new tab

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/dweb-search-frontend#132]
For example, on right click. Or as a default. I often want to check out several items at the same time, I am used to opening several leads in new tabs while navigating the list. Perhaps we might use normal `<a href>'`s, enabling browser's default behaviour, which Google, Duckduckgo and Startpage seem to do.

References
https://stackoverflow.com/questions/40015037/can-vue-router-open-a-link-in-a-new-tab
https://vuejsexamples.com/vue-js-right-click-menu/

**Comment by femans** [comment]
closed with #214
