### ISSUE TITLE
grey margins around images

### ISSUE THREAD

**Issue by femans** [ipfs-search/dweb-search-frontend#148]
Above and below are grey margins. There shouldn't be.
https://ipfs-search.com/#/search/detail/images/QmZ9yExr2QQGSXmhY5ybmJhD86LnS5w9s7xCqstn5GdC8b?q=kitten&page=1
<img width="376" alt="image" src="https://user-images.githubusercontent.com/625851/167634684-87eb90f8-a3d6-4d77-beec-5f081fcce9e7.png">

**Comment by femans** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/625851/166651464-5a87ef7f-7978-4553-ab56-3816e8dfb0ef.png">

**Comment by femans** [comment]
it seems that it is the background of the image, and it almost always fits the image in a frame too big. So there are really 2 issues here:

- the background does not match the surrounding color
- the frame is unnecessarily large, there is really no reason for these margins to be there in a landscape picture.

**Comment by dokterbob** [comment]
@Szeket Is this perhaps something you could pick up? 

Relevant code and CSS lives here:
https://github.com/ipfs-search/dweb-search-frontend/blob/master/src/components/results/detail/ImageDetail.vue
