### ISSUE TITLE
in list view, highlight item under the cursor

### ISSUE THREAD

**Issue by femans** [ipfs-search/dweb-search-frontend#167]
It would be nice to have some visual highlight of the item under the cursor, e.g. slightly brought 'upwards' (shift 3px NW and increase shadow), to invite clicking on it.

**Comment by femans** [comment]
@Szeket I never saw the PR, @dokterbob reviewed it and merged it apparently. I noticed it doesn't work very well in dark mode yet.

**Comment by Szeket** [comment]
Wow. Didn't know that! I will look it up 😊👌now

**Comment by Szeket** [comment]
https://github.com/vuetifyjs/vuetify/issues/11906 and https://github.com/vuetifyjs/vuetify/pull/12216

They have improved the visibility problem a bit, but it's not fixed. Also, I implemented these changes, but no effect.
