### ISSUE TITLE
Never finds any HTML or plaintext

### ISSUE THREAD

**Issue by Leonix** [ipfs-search/dweb-search-frontend#180]
Hey guys. It seems that ipfs-search frontend never shows any results with mimetype `'text/html'` or `'text/plain'`.

Consider this query: https://ipfs-search.com/#/search?q=HomeDashboardBlogStack%20Timeline

It shows empty result page. However, if I query the API directly (omitting the content-type condition), it clearly returns two HTML pages: https://api.ipfs-search.com/v1/search?type=file&page=0&q=HomeDashboardBlogStack+Timeline+last-seen%3A%5Bnow%2Fd-30d+TO+%2A%5D
```
{"total":2,"max_score":107.04616,"hits":[
    {"hash":"QmbFX3PEnf9651EuKrBMwdfNR675gh2TQzjCY7MfzY5CgA",...,"mimetype":"text/html"},
    {"hash":"QmZcJUMWYpbTG2zsM5xhfVncTMrCwBuAnkvoVR8iry7AG1",...,"mimetype":"text/html"}
],"page_size":15,"page_count":1}
```
Same with plaintext. Looks like content-type condition, as used by web UI, does not properly work. 

* * *

I believe this is because Tika includes charset as part of content type. As hinted by API call for metadata
https://api.ipfs-search.com/v1/metadata/QmbFX3PEnf9651EuKrBMwdfNR675gh2TQzjCY7MfzY5CgA
```
"Content-Type":["text/html; charset=UTF-8"]
```
Search condition used by web UI `metadata.Content-Type:"text/html"` does not include charset and does not work because of that. This query returns nothing:
https://api.ipfs-search.com/v1/search?type=file&page=0&q=metadata.Content-Type%3A%22text%2Fhtml%22

But if I add wildcard condition: `metadata.Content-Type:text\/html*` it properly returns HTML results:
https://api.ipfs-search.com/v1/search?type=file&page=0&q=metadata.Content-Type%3Atext%5C%2Fplain%2A

**Comment by femans** [comment]
Thanks @Leonix for the report. We will look at this issue soon.

**Comment by dokterbob** [comment]
Seems like an escaping issue in our content-type filter.

Code lives here: https://github.com/ipfs-search/dweb-search-frontend/blob/ee963a6032adde3c0f814c273f2f446e65438dbf/src/helpers/ApiHelper.js

@femans @Szeket @Leonix I think the content-type for `text/html` might have encoding data added, so requires a wildcard in the end. One of you perhaps able to give that a test run?

**Comment by dokterbob** [comment]
Example value of `Content-Type`:`text/html; charset=UTF-8`

@Leonix Great find!
