### ISSUE TITLE
Content-type filtering misses hits when field has more data than mimetype

### ISSUE THREAD

**Issue by femans** [ipfs-search/dweb-search-frontend#194]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/625851/170770654-02c267e5-c6da-4c5f-ac9e-edadc29f8167.png">
In the example given, the Content-type metadata field has value `text/plain; charset=UTF-8`. 

This should be classified as having mimetype 'text/plain' and show up under the documents/text filter. 
It doesn't do that because of the postfix `; charset=UTF-8`.

This can be solved by adapting the 'type'-filter definition to include wildcards for text/plain. 
But we also need to know if the same type of thing happens with other types and fix this. This can be done by investigating the search API or by looking for more examples. 
So:

- [ ] fix type filter definition for `text/plain` mimetype
- [ ] investigate which file types have `content-type` values that slip through the type filter. 
- [ ] fix type filter definition for those content-types.

**Comment by femans** [comment]
I tried adding an asterisk wildcard to the text/plain filter but this didn't work so far. Not sure why.

**Comment by dokterbob** [comment]
Isn't this a dup of #180, fixed in #185?

**Comment by femans** [comment]
Nope

**Comment by femans** [comment]
> Isn't this a dup of #180, fixed in #185?

The issue is more like a followup of this, revealed by #192; before this PR the hits simply never showed up so nobody was aware. Now they show up, and the bug is revealed.
