### ISSUE TITLE
Unf*ck alignment of language filter

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/dweb-search-frontend#195]
![image](https://user-images.githubusercontent.com/22742/170829392-0341f243-9a17-4c45-b054-779f1302e211.png)

This is the result of using a multi-select component whereas the others are single select. This is probably a bug in Vuetify. If it is, let's find the appropriate bug in their repo so we can track it here. As soon as it's closed there (or if it is already), we can upgrade Vuetify and we need do nothing more.

**Comment by femans** [comment]
The image you posted does not point out the issue, because the 2 filters on the right have something selected.

**Comment by femans** [comment]
closed with #214
