### ISSUE TITLE
Search doesn't work 

### ISSUE THREAD

**Issue by Szeket** [ipfs-search/dweb-search-frontend#217]
When entering a word, the results come like this:
![bug](https://user-images.githubusercontent.com/95712718/177760077-6f5b4fd2-cb52-4e98-a734-1e7f18809b68.jpg)
![bugg](https://user-images.githubusercontent.com/95712718/177760091-e9dec405-995e-428b-ac3e-141a182028d6.jpg)

the only result that goes through is "dog" ;)

**Comment by dokterbob** [comment]
I'm just getting results...
![image](https://user-images.githubusercontent.com/22742/177803505-74211895-6f10-4132-98eb-0f0b0105c341.png)

**Comment by Szeket** [comment]
![Screenshot at 2022-07-08 10-32-50](https://user-images.githubusercontent.com/95712718/177963298-84b015d6-de03-4348-8d0e-8f23f95215fe.png)

Still the same for me. Also @femans has the same issue?
