### ISSUE TITLE
Change the bottom bar behaviour

### ISSUE THREAD

**Issue by Szeket** [ipfs-search/dweb-search-frontend#223]
With some results, when there are few, the bottom bar does not disappear after scrolling down. It should disappear after one scroll down. Currently, one needs to scroll down to half the page, more or less. Otherwise, the bar is blocking the view. 

![Screenshot at 2022-07-28 16-02-20](https://user-images.githubusercontent.com/95712718/181572119-5df3967e-eadf-42fc-b37e-8a685f04b828.jpg)

**Comment by femans** [comment]
@Szeket why was this closed?

**Comment by Szeket** [comment]
Because you are fixing it with #226
