### ISSUE TITLE
Add a query parameter to allow direct links in search results

### ISSUE THREAD

**Issue by fabricedesre** [ipfs-search/dweb-search-frontend#281]
For Capyloon we'd like search results to link directly to their ipfs:// url since we have a local IPFS node that can fetch content.

An extra parameter in the query would work, and ideally that would be the part of the opensearch template.

**Comment by dokterbob** [comment]
Hi @fabricedesre, thanks for getting back on this one!

The code which renders lists lives here: https://github.com/ipfs-search/dweb-search-frontend/tree/staging/src/components/searchViewComponents

I'm not fully up to date on how we could work with request parameters vs. routes and state, but perhaps @femans can help you out with that. If he doesn't respond here, you might reach him directly on our matrix/telegram channel.

**Comment by femans** [comment]
Hi @fabricedesre please do reach out! I can look into it in the following days.

**Comment by fabricedesre** [comment]
> Hi @fabricedesre please do reach out! I can look into it in the following days.

What is the address of your Matrix room?

**Comment by femans** [comment]
`/search?nativeIpfs=true&q={...}` should be good, we need also to make it persistent so subsequent calls keep using this setting. I think we can add a setting to the settings menu with localStorage persistence.

**Comment by dokterbob** [comment]
> What is the address of your Matrix room?

[#ipfs-search:matrix.org](https://matrix.to/#/#ipfs-search:matrix.org)

**Comment by femans** [comment]
not changing settings. The query parameter should be enough for now.
