### ISSUE TITLE
Play button in audio detail should give feedback

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/dweb-search-frontend#44]
When going to the detail view of a song and clicking on play, I would expect that the play button changes into a loading indicator and then into a pause button. Instead, the player on the bottom starts loading but I won't notice as I am clicking in the middle in front of me and that's where I expect to see feedback.

Ref: https://github.com/ipfs-search/dweb-search-frontend/issues/43

**Comment by femans** [comment]
https://github.com/ipfs-search/dweb-search-frontend/tree/issue-%2344-play-button-feedback @vandrongelen Here you go, you can style it up, add more controls, do whatever you like now to the detail page. Btw it already works with this branch

**Comment by femans** [comment]
@dokterbob FYI I discussed this yesterday with Kees and abstracted the controls and the audio player such that now the play button can 'know' if it's song is currently playing.
