### ISSUE TITLE
Mimetype and download irrelevant for directories

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/dweb-search-frontend#47]
In directory detail views, we can see 'mimetype' with no actual mimetype (as directories have no mimetype). There is also a download button which is not relevant for directories.

This issue possibly requires #41 to be closed before it can be seen.

Ref: https://github.com/ipfs-search/dweb-search-frontend/issues/43

**Comment by femans** [comment]
#41  is closed, I know why this is, it is because I put the standard MediaHeader component there and this is not applicable. Should be something custom for directories
