### ISSUE TITLE
Load all dependencies over IPFS (instead of external URLs)

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/dweb-search-frontend#85]
We are currently loading quite a few external dependencies over normal HTTP.

For example, [fonts](https://github.com/ipfs-search/dweb-search-frontend/blob/master/public/index.html#L10). We should either use WebPack to include them or simply download files into the 'pub' dir and load them locally (as we do with favicon).

**Comment by madnificent** [comment]
- https://git.rys.io/rysiek/fonts-degooglifier
  - https://google-webfonts-helper.herokuapp.com/fonts
