### ISSUE TITLE
Load search results for swiper in background for detail view

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/dweb-search-frontend#92]
Although basic rendering works for detail views, I think we should request relevant search results in the background to enable swiping.

I would suggest this works as follows:
1. Render detail view based on data in URL/route
2. Request search results based on data in URL/route
3. Find index of current item in search results
4. IF and ONLY IF item is found, enable swiping

Does that sound sensible?

Related to #73

**Comment by femans** [comment]
i am not sure what you mean. But it may have been implemented by the latest PR.
